
# See https://doc.mergify.io

queue_rules:
  - name: default
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
pull_request_rules:
  - name: automatic merge
    actions:
      comment:
        message: Thank you for contributing! Your pull request is now being automatically merged.
      queue:
        method: squash
        name: default
        commit_message_template: |-
          {{ title }} (#{{ number }})
          {{ body }}
      delete_head_branch: {}
      dismiss_reviews: {}
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
  - name: remove stale reviews
    actions:
      dismiss_reviews:
        approved: true
    conditions:
      - author!=aws-cdk-automation
      - base=main
      - -merged
      - -closed
